server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: log-generator
  pipeline_stages:
  - match:
      selector: '{job="log-generator"}'
      stages:
      - regex: 
          # extract http response from message
          expression: '^(?P<ip>.*) - - \[(?P<timestamp>(.*))] \"(?P<http_verb>\S*) \S* \S*\" (?P<http_status_code>.*) '
      - labels:
          # I don't want the timestamp to become labels, but it is relevant.  Not sure what to do with this yet.
          # timestamp:
          http_verb:
          http_status_code:

  static_configs:
  - targets:
      - localhost
    labels:
      job: log-generator
      __path__: /var/log/apache_access
