server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: csv_demo
  # pipeline_stages:
  # - 
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.csv
- job_name: lignator_job
  pipeline_stages:
  - match:
      selector: '{job="lignatorlogs"}'
      # selector: ''
      stages:
      - regex: 
          # extract severity from message
          expression: '\[(?P<severity>[a-zA-Z]+\s*)\]'
      - labels:
          severity:
    
  static_configs:
  - targets:
      - localhost
    labels:
      job: lignatorlogs
      __path__: /var/log2/*.log
